### ISSUE TITLE
It does not work on modified buffers due to 'edit AerojumpFilter'

### ISSUE THREAD

**Issue by resolritter** [philip-karlsson/aerojump.nvim#5]
Hello! Trying to use `:edit` from a modified buffer does not work. This happens when you try to aerojump before saving the code, for instance.

I personally was satisfied with the following solution.

```diff
    def __open_aerojump_filter_buf(self, filter_string = ''):
-        self.nvim.command('edit AerojumpFilter')
+        self.nvim.command('tabedit AerojumpFilter')
```

```diff
    @neovim.command("AerojumpExit", range='', nargs='*', sync=True)
    def AerojumpExit(self, args, range):
        """ Exit aerojump without moving the selection

        Parameters:
            n/a

        Returns:
            n/a
        """
        self.nvim.command('stopinsert')
        self.nvim.current.buffer = self.og_buf
        self.nvim.command('bwipeout %s' % self.aerojump_buf_num)
        self.nvim.command('bwipeout %s' % self.filt_buf_num)
+        self.nvim.command('tabclose')
        # Restore original position
        self.nvim.current.window.cursor = self.top_pos
        self.nvim.command('normal! zt')
        self.nvim.current.window.cursor = self.og_pos
```

The downside is that it has to create a tab. Another idea would be to open a floating window at full-width/full-height instead, and then issue `nvim_win_close` instead of `tabclose`.

Are you interested in this approach? If so, I could submit a PR.

**Comment by ripxorip** [comment]
Cool, I think this shall be a setting instead where the default behavior is to spawn a new buffer but with this new option a tab is used? I would love a PR.
