### ISSUE TITLE
Weird behavior when trying to run space search

### ISSUE THREAD

**Issue by FuzzOli87** [philip-karlsson/aerojump.nvim#8]
Hello,

Whenever I try to run the space search, I get this:
![image](https://user-images.githubusercontent.com/12246915/66673472-40b49680-ec26-11e9-9b9c-c21ff22ddc25.png)

Might be hard to see, but the actual file contents end up in the bottom where the filter is supposed to be happening and the screen is replaced by a black screen.

**Comment by ripxorip** [comment]
Hi! I will look in to it asap, that is not the correct behaviour. Could you try to revert to 36812c17e67fae55898ef1eaf2326d4102e58b05 and see if it is still present?

**Comment by ripxorip** [comment]
Just tried it out on my machine and it seems to be working as expected. Do you have some more information about your environment? Dockerfile? Are you using the latest commit on master?

**Comment by ripxorip** [comment]
Any update on the testing?

**Comment by FuzzOli87** [comment]
Hey! Sorry for the late reply!

So, I disabled every other plugin except for my theme and I saw the same result. I'm running on Catalina as of late so maybe that is the problem? I was seeing aerojump not show up on the python logs when I did ```UpdateRemotePlugins``` at first.

**Comment by FuzzOli87** [comment]
@ripxorip I know what it is. I have the configurations 
```
set splitbelow
set splitright
```

**Comment by ripxorip** [comment]
Thx for getting back to me. I see, not sure if there is something I can do in the plugin to solve that specific behavior? Maybe change those specific settings for buffers related to aerojump perhaps?
