### ISSUE TITLE
Feature request: new mode

### ISSUE THREAD

**Issue by hissssst** [philip-karlsson/aerojump.nvim#9]
I thought that it would be nice to have search mode like `AerojumpSpace`, but with a few changes
1) Selected text and selected lines are highlighted and colored just like they are colored in `AerojumpSpace`
2) Other lines are colored in grey or any other monotonic color (possibly comment color)

**Comment by ripxorip** [comment]
Hi, I have had the same idea a while ago but never got around to implement it. Should be pretty straight forward. Will try to look in to it.

**Comment by hissssst** [comment]
@ripxorip https://github.com/ripxorip/aerojump.nvim/pull/10

**Comment by ripxorip** [comment]
Milk mode! Love it!!
